name: "Second action"
on:
  workflow_run:
    workflows: ["First action"]
    types: [completed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        npm install
        npm run all

  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      id: filter
      with:
        filters: |
          src:
            - src/**
          tests:
            - __tests__/**
    - name: filter-test
      run: |
        echo '${{ toJSON(steps.filter.outputs) }}'
